# Generated by Django 4.2.5 on 2023-09-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_alter_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='ims',
            new_name='ism',
        ),
    ]
